### ISSUE TITLE
Please document prerequisites for using DQL

### ISSUE THREAD

**Issue by perlausten** [icstechsales/dql-explorer#13]
Please document how to update the required design catalog in order for DQL to work - or at least state that this is required in order for DQL to work. Thanks.

**Comment by dprosper** [comment]
Definitely will not duplicate the docs for DQL, but agree will provide a requirements section in readme pointing to the DQL documentation.  

btw: We also accept pull requests :-)

**Comment by perlausten** [comment]
@dprosper thanks, and point taken wrt. pull requests. I am happy to do so once we get it to work :-)

**Comment by dprosper** [comment]
I added a section in the readme with a link to the steps in the DQL documentation.  Hopefully, this will help others: https://github.com/icstechsales/dql-explorer#requirements

What difficulties are you experiencing in setting it up or are you all set now?

**Comment by perlausten** [comment]
We have run the necessary steps to create the design catalog:

**> load updall sherlock/winetastings21.nsf -e**
```
03/11/2019 02:57:50 PM  Index update process started:  sherlock/winetastings21.nsf -e
03/11/2019 02:57:50 PM  Updating views in C:\Program Files\IBM\Domino\data\sherlock\winetastings21.nsf
03/11/2019 02:57:51 PM   65 catalog documents removed, 15 view designs cataloged out of 15 total with 44 collations in 367.99 msecs
03/11/2019 02:57:51 PM  Index update process shutdown

``` 
**> load updall sherlock/winetastings21.nsf -d**
```
03/11/2019 02:58:01 PM  Index update process started:  sherlock/winetastings21.nsf -d
03/11/2019 02:58:01 PM  Updating views in C:\Program Files\IBM\Domino\data\sherlock\winetastings21.nsf
03/11/2019 02:58:01 PM   0 catalog documents removed, 0 view designs cataloged out of 0 total with 0 collations in 14.300 msecs
03/11/2019 02:58:01 PM  Index update process shutdown
```

When we then try to run a query, DQL Explorer responds with: "_Domino Query execution error: Entry not found in index - validation error Error validating view column name - ['SubTastingVintage'.$4] .. invalid view name or database needs to be cataloged via updall -e(Call hint: NIFCalls::NIFFindByKeyExtended2, Core call #0)******************_" and the server logs shows "_HTTP Server: Agent 'runDQLQuery' error: No RESUME_".

**Comment by dprosper** [comment]
Try using a query against the forms first, like the SubEdit form.   I have not looked at this database closely, but I believe for DQL to work against the views, these may need to be modified as described here: https://doc.cwpcollaboration.com/appdevpack/docs/en/domino-query-language.html#identifying-view-columns-used-by-dql-processing

**Comment by dprosper** [comment]
@perlausten is there anything we need to do more on this issue or are we good to close it?
