### ISSUE TITLE
'DefaultButton' is defined but never used  no-unused-vars

### ISSUE THREAD

**Issue by eknori** [icstechsales/dql-explorer#14]
Compiled with warnings.

./src/components/querybuilder/ShareDialog.js
  Line 3:  'DefaultButton' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

TODO: remove DefaultButton from line 3 ; it has been used in line 73, but line 73 is commented out.

**Comment by dprosper** [comment]
merged
