### ISSUE TITLE
Error parsing timedate string

### ISSUE THREAD

**Issue by eknori** [icstechsales/dql-explorer#16]
Resulting query contains wrong timedate string

Domino Query execution error: Release 10.0.1|November 29, 2018 - error during planning and tree generation Error parsing timedate string - 2019-21-13 (ISO massaged string = 20192113)Error filling node for timeTimeFrom = '2019-21-13' (Call hint: OSLocalAllc, Core call #0)******************

![timedate](https://user-images.githubusercontent.com/3882620/54257437-99706380-455f-11e9-9176-7a49c2617fb2.jpg)

**Comment by dprosper** [comment]
We also encountered this issue internally and produced this update https://github.com/icstechsales/dql-explorer/commit/5a268f1f3cf7d07711352a4ac549343b7aeb1f92 which addresses that issue.  You can pull the latest code/template to use it.  or modify your copy based on the small changes described in the update.

**Comment by eknori** [comment]
Excellent. Works now.
