### ISSUE TITLE
Readme.md misleading

### ISSUE THREAD

**Issue by vju42** [icstechsales/dql-explorer#25]
There's two stories told in readme.md: 
1. For the DQL Newbie to try DQL via DQL explorer. For this we need a crisp intro that simply focuses on getting the nsf on the disk and prereqs set up
2. For building the NTF from scratch 

Currently, these stories are mixed - basically it starts with story 1, then deep dives in story 2 and the last line finally is the missing piece of story 1.

Let's make this help wanted and i'm ready to work on this

**Comment by dprosper** [comment]
you got it

**Comment by vju42** [comment]
I've made a first update and created a pull request - have a look

**Comment by dprosper** [comment]
thank you for your contribution @vju42
