### ISSUE TITLE
Query does not take selected FORM into account

### ISSUE THREAD

**Issue by eknori** [icstechsales/dql-explorer#9]
I have created a database with 2 forms ( form1 and form2 ) . Both forms have an item with name 'subject'
I also have created douments for each form.

I have configured a query to get all documents from the database that are of type form1 AND have the word form in 'subject'

DqlExplorer builds the correct query in the Development Options sections, but the submitted qury is missing the Form="form1" part. 

The result is 2 documents, but this also includes the document created with form2

![dqlissue002](https://user-images.githubusercontent.com/3882620/54070787-fb318480-4264-11e9-9dee-91e557cbbbdf.jpg)

**Comment by dprosper** [comment]
Thank you for reporting this issue, we've addressed that in a new release: https://github.com/icstechsales/dql-explorer/releases
